### ISSUE TITLE
I'm lost

### ISSUE THREAD

**Issue by MaximusOldham** [MaximusOldham/gnarly#1]
Before I proceed any further, I just need someone to look over what I've done so far. Every route I've taken and person that I've asked for help can not figure it out. I know this isn't the 5 minute question, but I just don't know what to do and I'm in dire need of help. Sorry for any inconvenience. -Max

**Comment by tambling** [comment]
If this is a question about your ERD, or how to model your data or architect your app, you're welcome to come to us at any time. Otherwise, please come to us with a specific user story you're working on, in accordance with the [issue submission guidelines](https://github.com/ga-students/WDI_DTLA_6/tree/master/projects/project_issues_protocol).

Also, your last commit was two days ago– if you've made changes since then, it would be helpful for you to commit and push them, so we can see the code you've written.

**Comment by MaximusOldham** [comment]
Unfortunately everything I did yesterday blew up, nothing would work (and everyone that helped- including TA's last night- couldn't figure it out, so I couldn't commit anything. I believe I've messed up naming a migration which has caused confusion in naming everything else in every file. I'm not sure whether to just delete it all and start over or not.

**Comment by tambling** [comment]
Don't do that. Commit and push what you have, even though it doesn't work, and I'll take a look at it. What specific error are you getting, and when?

**Comment by MaximusOldham** [comment]
When I am trying to make a post (gnarlie)... https://i.imgur.com/tXXd7Mz.png
But I believe the problem is a lot more complex than that.

**Comment by tambling** [comment]
So, Rails partials can't see instance variables– you need to pass them in as arguments. [This StackOverflow answer](http://stackoverflow.com/questions/2503838/rails-should-partials-be-aware-of-instance-variables) has a good explanation/solution.

**Comment by tambling** [comment]
Also, I don't actually know where this partial is being rendered from. Wherever it's being rendered, make sure that `@gnarlie` is actually set.
