### ISSUE TITLE
Missing Template error

### ISSUE THREAD

**Issue by MaximusOldham** [MaximusOldham/gnarly#2]
I'm trying to create a new gnarlie(post) and I feel like I have everything in the right place but I'm still getting this error. Can you help?
https://i.imgur.com/HXIZnyy.png

**Comment by ezRAez** [comment]
Your issue is in the naming of your "gnarlie.html.erb". Partials start with
an underscore (ie: _gnarlie.html.erb), otherwise you cannot render the page
within another page.

On Wed, Nov 4, 2015 at 12:41 PM, Max notifications@github.com wrote:

> I'm trying to create a new gnarlie(post) and I feel like I have everything
> in the right place but I'm still getting this error. Can you help?
> https://i.imgur.com/HXIZnyy.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MaximusOldham/gnarly/issues/2.

## 

-ezRAez
Instructional Associate
General Assembly | DTLA
_ezra.raez@generalassemb.ly ezra.raez@generalassemb.ly_ | _ga.co
http://ga.co/_

**Comment by ghost** [comment]
Closing. If you still have this issue, you can re-open!

**Comment by MaximusOldham** [comment]
I did this and still nada : /
I've had several people/students come look at this and the TA last night... Any other recommendations?
